sexualkeywords = [
"couples",
"sexual",
"positions",
"harassment",
"assault",
"act",
"intercourse",
"offenders",
"violence",
"predators",
"abuse",
"child abuse",
"mens health",
"stories",
"funk",
"intercourse positions",
"world records",
"massage",
"intercourse videos",
"harassment lawyers",
"education and public schools",
"massage videos",
"fantasies",
"discrimination",
"astrology",
"abuse of boys",
"prozac",
"intercourse video",
"workplace harassment",
"women getting massage",
"registry",
"intercourse pictures",
"harassment videos",
"harassment training",
"harassment law",
"fetishes",
"fantasies stories",
"freya fantasies",
"torture",
"positions video",
"positions illustrated",
"encounters",
"arousal",
"addiction",
"incest and fantasy stories",
"swingers desires",
"predators",
"enhancement",
"slang",
"seduction",
"punishment",
"orientation",
"offender registry",
"intercourse photos",
"harrassment",
"harassment policy",
"harassment cases",
"enhancement",
"addictions support groups",
"public humiliation",
"sexually transmitted disease",
"childhood abuse",
"bi-sexual couples",
"adult massage",
"womens health",
"womens enhancement",
"virtual sexual devices",
"bi sexual couples",
"stiff nights",
"sexual well being",
"sexual video chat software",
"truth or dare",
"STD",
"sexual role playing",
"sexual reproduction",
"sexual relationship in family",
"sexual relations",
"sexual pursuit",
"sexual punishment stories",
"predator list",
"performance enhancement",
"penetration",
"child abuse",
"bi sexual",
"asexual",
"childhood abuse",
"compatibility"

                  ]

financekeywords = [
"tips",
"affiliate program",
"wordpress themes",
"skills",
"job hunting sites",
"job hunting",
"successful",
"job hunting for seniors",
"advice 'new nurses'",
"win mississippi",
"dummies",
"the handbook",
"online versus traditional",
"websites",
"time management",
"good will",
"words of encouragement",
"wisconsin illinois",
"walmart",
"vetern",
"us government",
"unwritten rules",
"under 18 dublin",
"unconventional",
"uk sites",
"twitter",
"transferrable skills",
"top us sites",
"top books",
"top blogs",
"top 10 sites",
"the ex-offender guide",
"test your skills",
"telecom",
"teenager",
"teen",
"technical writing",
"tech writing",
"taxes expenses",
"tax write-off",
"tax write off",
"tax deductions",
"tax deduction expenses",
"summer tips",
"successfull techniques",
"successful tips",
"strategies",
"strategic",
"staying positive",
"start a website",
"speculative",
"specialises in advice",
"best sites",
"cover letters",
"hunting internet job",
"hunting job",
"resume",
"company",
"local job hunting",
"service",
"monster",
"find a job",
"job"

#
"finance",
"yahoo",
"personal",
"car finance",
"international",
"auto",
"corporation",
"international corporation",
"corporate",
"loan",
"banking and",
"automotive",
"job hunting",
"company",
"premium",
"mortgage",
"loan",
"credit",
"calculator",
"department of finance",
"mortgage",
"manager",
"finance software",
"credit",
"honda",
"companies",
"insurance",
"general finance",
"housing",
"personal software",
"real estate",
"capital",
"hyundai motor",
"yahoo",
"nissan finance",
"chase auto",
"carmax auto",
"security",
"kia motors",
"world finance",
"exeter",
"hyundai",
"kia",
"dept of finance",
"progressive",
"cedar",
"daily finance",
"wells fargo auto finance",
"heights finance",
"kia motor",
"southeast toyota",
"toyota",
"american general",
"chase auto",
"continental",
"republic",
"yahoo stock quotes",
"finance express",
"google finance portfolio",
"msn",
"yahoo finance news",
"carmax",
"mid atlantic",
"beneficial",
"capital one",
"auto sales",
"robert half finance",
"senate committee",
"bmw",
"subaru motors",
"world corporation",
"santander consumer",
"best personal finance software",
"defense and accounting service",
"thrift",
"infiniti",
"new york city department of finance",
"residential corporation",
"subaru",
"campaign reform",
"capital one",
"emory",
"entry level jobs",
"masters in finance",
"world finance loans",
"car offers",
"amazing photo",
"business news",
"car rates",
"zip news",
"hunting"

                    ]

marketingkeywords = [
"marketing advertising",
"advertising",
"marketing",
"public relations",
"internet advertising",
"advertising business",
"online advertising",
"advertising services",
"web advertising",
"advertising media",
"promotion",
"advertising direct",
"website",
"sales",
"online business",
"customer product pay",
"agency",
"insurance summit",
"consultants",
"affiliate",
"small business",
"retail",
"strategy",
"campaign",
"branding",
"direct mail",
"online media",
"recruitment",
"promotions",
"products",
"internships",
"integrated",
"hispanic",
"web site compliance",
"web promotion",
"marketing advertising website",
"sports agency",
"publicity",
"integrated advertising promotion",
"integrated marketing communications",
"advertising promotion",
"services",
"strategies",
"understanding cultural paradoxes",
"internet services",
"online business",
"business healthcare",
"schools for marketing and advertising",
"agencies",
"integrated advertising promotion",
"colleges for advertising and marketing",
"public relations",
"sales managers"

                     ]
                     
abnormalkeywords = sexualkeywords + financekeywords + marketingkeywords